services:
    aurelienazerty.nomixedcontent.listener:
        class: aurelienazerty\nomixedcontent\event\listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }